import javax.swing.JOptionPane;
public class DiceSolution 
{
	private static String userSelection;
	private static String endGame;
	
	private int winNumber;
	private int caseOdd;
	private int caseEven;
	private int numberOfGamePlayed;
	
	public static void Welcome()
	{
		JOptionPane.showMessageDialog(null, "Welcome to Game of Dice");
	}
	
	public static String UserSelection()
	{		
		do
		{
			userSelection = JOptionPane.showInputDialog("Please enter your selection, either odd or even");
			if(!userSelection.equalsIgnoreCase("odd") && !userSelection.equalsIgnoreCase("even"))
			{
				JOptionPane.showMessageDialog(null, "Please enter either odd or even");			
			}
		}while(!userSelection.equalsIgnoreCase("odd") && (!userSelection.equalsIgnoreCase("even")));
		
		return userSelection;// = JOptionPane.showInputDialog("Please enter your selection, either odd or even");
	}
	
	public void DiceStratergy()
	{
		RandomOddEven dice = new RandomOddEven();
		
		switch(userSelection)
		{
		case "odd":
			/*switch(dice.GetDice())
			{
			case 1:
				JOptionPane.showMessageDialog(null, "You win" + " (" + dice.GetDice() + ")"); break;
			case 3:
				JOptionPane.showMessageDialog(null, "You win" + " (" + dice.GetDice() + ")"); break;
			case 5:
				JOptionPane.showMessageDialog(null, "You win" + " (" + dice.GetDice() + ")"); break;	
			case 2:
				JOptionPane.showMessageDialog(null, "You lose" + " (" + dice.GetDice() + ")"); break;
			case 4:
				JOptionPane.showMessageDialog(null, "You lose" + " (" + dice.GetDice() + ")"); break;				
			case 6:
				JOptionPane.showMessageDialog(null, "You lose" + " (" + dice.GetDice() + ")"); break;
			}*/
			
			if(dice.GetDice() == 1 || dice.GetDice() == 3 || dice.GetDice() == 5)
			{
				JOptionPane.showMessageDialog(null, "You win" + " (" + dice.GetDice() + ")");
				winNumber++;
				caseOdd++;
			}
			if(dice.GetDice() == 2 || dice.GetDice() == 4 || dice.GetDice() == 6)
			{
				JOptionPane.showMessageDialog(null, "You lose" + " (" + dice.GetDice() + ")");
				caseEven++;
			}
		break;
		case "even":
			if(dice.GetDice() == 1 || dice.GetDice() == 3 || dice.GetDice() == 5)
			{
				JOptionPane.showMessageDialog(null, "You lose" + " (" + dice.GetDice() + ")");
				caseOdd++;
			}
			if(dice.GetDice() == 2 || dice.GetDice() == 4 || dice.GetDice() == 6)
			{
				JOptionPane.showMessageDialog(null, "You win" + " (" + dice.GetDice() + ")");
				winNumber++;
				caseEven++;
			}
		break;
		}
		
		numberOfGamePlayed++;
	}
	
	public static String ExitGame()
	{
		do
		{
			endGame = JOptionPane.showInputDialog("Continue to play, yes or no");
			if(!endGame.equalsIgnoreCase("yes") && !endGame.equalsIgnoreCase("no"))
			{
				JOptionPane.showMessageDialog(null, "Please enter either yes or no");			
			}
		}while((!endGame.equalsIgnoreCase("yes")) && (!endGame.equalsIgnoreCase("no")));
		
		return endGame;
	}
	
	public void GameReport()
	{
		//float percentageWin = ((winNumber*100.0f)/numberOfGamePlayed);
		float percentageOddGuess = (caseOdd*100.0f)/numberOfGamePlayed;
		float percentageEvenGuess = (caseEven*100.0f)/numberOfGamePlayed;
		//print the number of odd/even guesses, percentage win, percentage odd number generated
		//and number of game played.
		String messagesToPrint = "Number of games you played " + String.valueOf(numberOfGamePlayed)  + "\n" + 
		"Number of games you win " + winNumber + "\n" + 
		"Percentage even guesses entered by player "  + percentageEvenGuess + "%" + "\n" +
		"Percentage odd number generated by Dice " + percentageOddGuess + "%" + "\n" +
		"Thanks for playing!!!";
				
		JOptionPane.showMessageDialog(null,messagesToPrint);
	}
}
